---
# By setting the language to node_js, travis will execute the follwing steps:
# 1. Install the required node.js version (including npm)
# 2. Install dependencies with `npm install`
# 3. Execute tests with `npm travis`
language: node_js
node_js:
  - '0.10'
  
# We need a running neo4j-instance for our end2end-tests.
# The neo4j-server will listen on the standard port (7474)
services:
  - neo4j
  
# We use the grunt command-line tool for test execution, so we
# have to make sure, that the grunt executable is available
before_script:
  - npm install -g grunt-cli

# See http://about.travis-ci.org/docs/user/deployment/heroku/ for
# more information on automatic deployment to heroku
deploy:
  provider: heroku
  app: fuh-team-3
  api_key:
    secure: ! 'aTbOfcWjA/IYF2X2hQDEcfj8P+yKIDz6pBiIGx9agf0dmgGU3IoBtu6ySrjB
      4IzChzbUXQ6kQV+lhh57tQ+bdgyO5dqs9mCWSA2+dkB/8W3WuUszoabvVC0v
      TNcnznAS3KB1T7oKZEmquYuPgHcJFvn1gwLtxU7UCFFOItVFSiQ='
                
                
